# Generated by Django 4.2.28 on 2026-02-10 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_name', models.CharField(help_text='Food or meal description', max_length=200)),
                ('protein_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fat_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('carbs_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_calories', models.DecimalField(blank=True, decimal_places=2, help_text='Optional: auto from 4*protein + 9*fat + 4*carbs if blank', max_digits=8, null=True)),
                ('water_ml', models.PositiveIntegerField(default=0, help_text='Water in ml (e.g. 250 for a glass)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nutrition Log',
                'verbose_name_plural': 'Nutrition Logs',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
