# Generated by Django 4.2.28 on 2026-02-10 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('goal', models.CharField(max_length=10)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi_category', models.CharField(blank=True, max_length=20, null=True)),
                ('bmr', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('daily_calories', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('daily_protein_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('daily_fat_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('daily_carbs_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('daily_water_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Data',
                'verbose_name_plural': 'Health Data',
                'ordering': ['-created_at'],
            },
        ),
    ]
